#import "./template.typ": *

#show: template.with(
    title: "Advanced Probability",
    short_title: "Note of Probability: Theory and Examples by Rick Durrett",
    description: "Notes based on Book: Probability: Theory and Examples by Rick Durrett",
    paper_size: "a4",
    cols: 1,
    text_font: ("Palatino", "STIX Two Text", "Noto Serif SC"),
    code_font: ("Fira Code", "Monaspace Neon", "LXGW WenKai Mono"),
    accent: "#1A41AC",
    colortab: true,
    h1-prefix: "Chapter",
)

#pagebreak()

= Measure Theory

== Probability Spaces

一个 *概率空间/Probability Space* 是一个三元组 $(Omega, cal(F), P)$，其中 $Omega$ 是结果/Outcomes 的集合，$cal(F)$ 是事件/Events 的集合，而 $P: cal(F) arrow [0, 1]$ 是一个给事件分配概率的函数。我们假设 $cal(F)$ 是一个 *$sigma$-代数/$sigma$-Algebra*，即 $Omega$ 的子集的一个非空集合，满足对可数交、可数并和补集运算的封闭性。仅给定 $(Omega, cal(F))$，我们称之为 *可测空间/Measurable Space*，即我们可以通过其定义测度的空间，所谓测度是一个非负的、可数可加的函数，即一个函数 $mu: cal(F) arrow RR$，满足

- 对所有 $A in cal(F)$，$mu(A) >= mu(diameter) = 0$；
- 若 $A_i in cal(F)$ 是互不相交的集合序列，则 $mu(union.big_i A_i) = sum_i mu(A_i)$。

如果对于全集 $Omega$，$mu(Omega) = 1$，我们称 $mu$ 是一个 *概率测度/Probability Measure*。在本书中，概率测度通常用 $P$ 表示。

#theorem()[
    令 $mu$ 是 $(Omega, cal(F))$ 上的一个测度，则 $mu$ 满足下面性质：

    1. *单调性/Monotonicity*。如果 $A subset B$，则 $mu(A) <= mu(B)$；
    2. *次可加性/Subadditivity*。如果 $A subset union.big_(m=1)^infinity A_m$，则 $mu(A) <= sum_(m=1)^infinity mu(A_m)$；
    3. *下连续性/Continuity from below*。如果 $A_i arrow.t A$，换句话说 $A_1 subset A_2 subset ...$ 并且 $union.big_i A_i = A$，则 $mu(A_i) arrow.t mu(A)$；
    4. *上连续性/Continuity from above*。如果 $A_i arrow.b A$，换句话说 $A_1 supset A_2 supset ...$，$inter.big_i A_i = A$，且 $mu(A_1) < infinity$，则 $mu(A_i) arrow.b mu(A)$。
]

#proof()[
    1. 由于 $B = A union (B inter A^c)$，可以知道 $mu(B) = mu(A) + mu(B inter A^c) >= mu(A)$；
    2. 令 $A_n^prime = A_n inter A$，$B_1 = A_1^prime$，$B_n = A_n^prime - union.big_(m=1)^(n-1) A_m^prime$，则 $B_n$ 互不相交且 $union.big_m B_m = A$，还有 $B_n subset A_n$，所以 $mu(A) = sum_(m=1)^infinity mu(B_m) <= sum_(m=1)^infinity mu(A_m)$；
    3.
]

注意到，如果 $cal(F)_i$ 是一列 $sigma$-代数，那么其交 $inter.big_i cal(F)_i$ 也是一个 $sigma$-代数。如果我们给定一个集合 $Omega$ 和 $Omega$ 的子集的集合 $cal(A)$，那么存在包含 $cal(A)$ 的最小 $sigma$-代数。我们将此称为 *由 $cal(A)$ 生成的 $sigma$-代数* 并记为 $sigma(cal(A))$。

下面记 $bold(R)^d$ 为实数向量 $(x_1, dots x_d)$ 的集合，$cal(R)^d$ 为 Borel 集合，即包含开集的最小 $sigma$-代数。我们可以如下定义 Stieltjes 测度函数和 Lebesgue 测度：

#theorem()[
    在 $(bold(R), cal(R))$ 上定义的测度 $F$ 如果满足下面性质：
    - $F$ 是非减的；
    - $F$ 是右连续的，即 $lim_(y arrow.b x) F(y) = F(x)$；
    那么称 $F$ 是一个 *Stieltjes 测度函数/Stieltjes Measure Function*。与这个 Stieltjes 测度函数 $F$ 对应，在 $(bold(R), cal(R))$ 上存在唯一的测度 $mu$，满足 $mu((a, b]) = F(b) - F(a)$。当 $F(x) = x$ 时，产生的测度称为 *勒贝格测度/Lebesgue Measure*。
]<label:theorem-1-1-2>

这个定理的难点在于，我们只知道测度在半开区间 $(a, b]$ 上的取值，但是测度的定义域是 $sigma$-代数，我们需要完成定义域的扩展，并且保证扩展后的测度唯一。证明这个定理的过程漫长而曲折，我们仅仅需要学习其主要思路。首先，我们需要知道为什么这里选择的是左开右闭区间。至于 *为什么是右闭*，是因为如果 $b_n arrow.b b$，则 $inter.big_n (a, b_n] = (a, b]$。至于 *为什么是左开*，我们将在下面的定义 *半代数/Semialgebra* 以及 *代数/Algebra* 中看到。

#definition("半代数/Semialgebra")[
    一个集合族 $cal(S)$ 如果满足下面性质，那么称 $cal(S)$ 是一个 *半代数/Semialgebra*。
    1. 对交运算封闭，即如果 $S, T in cal(S)$，那么 $S inter T in cal(S)$；
    2. 如果 $S in cal(S)$，则 $S^c$ 可以表示成 $cal(S)$ 中若干集合的有限个两两不交并。
]

#definition("代数/Algebra")[
    全集 $Omega$ 的子集的集合 $cal(A)$ 如果满足下面条件，那么称之为一个 *代数/Algebra*。
    1. 对补集运算封闭，即如果 $A in cal(A)$，那么 $A^c in cal(A)$；
    2. 对并运算封闭，即如果 $A, B in cal(A)$，那么 $A union B in cal(A)$。
    显然代数对交运算也封闭，因为 $A inter B = (A^c union B^c)^c$。
]

这三类集合族有着明确的包含关系：半代数 $subset$ 代数 $subset$ $sigma$-代数。半代数和代数都要求对可数交运算封闭，而 $sigma$-代数要求对有限交封闭；半代数的补运算封闭性更弱，要求补集可以表示成有限个两两不交集合的并；而代数和 $sigma$-代数要求补集本身就属于集合族。这就直接证明了包含关系。

至于为什么选择左开右闭区间，左开右闭区间 $(a, b]$ 构成了实数轴上的一个半代数，而关于半代数的测度是最好定义的，但是半代数对于并不封闭，就需要扩展到代数，然后再扩展到 $sigma$-代数来解决极限行为。下面引理解释了这个逐步扩张的过程：

#lemma("From Semialgebra to Algebra")[
    如果 $cal(S)$ 是一个半代数，则 $overline(cal(S)) = { text("finite disjoint unions of sets in") cal(S) }$ 是一个代数，称为 *由 $cal(S)$ 生成的代数* / *Algebra generated by $cal(S)$*。
]<label:lemma-1-1-1>

#proof()[
    设 $A = +_i S_i$，$B = +_j T_j$，其中 $+$ 表示不交并，且我们假设这里面的指标集是有限的，那么
    $
        A inter B = +_(i, j) (S_i inter T_j) in overline(cal(S)).
    $
    也就是说 $overline(cal(S))$ 对有限交运算封闭，再看补集：如果 $A = +_i S_i$，则
    $
        A^c = inter_i S_i^c.
    $
    这里面 $S_i^c$ 都是 $cal(S)$ 中集合的有限不交并，肯定在 $overline(cal(S))$ 中，使用 $overline(cal(S))$ 关于有限交封闭，就可以得到 $A^c in overline(cal(S))$。
]

给定一个在 $cal(S)$ 上的集合函数 $mu$，我们可以把它扩展到 $overline(S)$ 上：参照 @label:lemma-1-1-1 的方法，如果 $A_i$ 两两不交，则定义
$
    mu(+_(i=1)^n A_i) = sum_(i=1)^n mu(A_i).
$
进一步可以在代数上定义 *测度*：

#definition("Measure on an Algebra")[
    设 $cal(A)$ 是一个代数，如果一个集合函数 $mu$ 满足下面条件，那么称 $mu$ 是 *代数 $cal(A)$ 上的测度*：
    1. 对所有 $A in cal(A)$，$mu(A) >= mu(diameter) = 0$；
    2. 若 $A_i in cal(A)$ 两两不交且它们的并仍属于 $cal(A)$，则
    $
        mu(union.big_i A_i) = sum_(i=1)^infinity mu(A_i).
    $
]

如果 $mu$ 满足下面条件，存在一列集合 $A_n in cal(A)$ 使得 $mu(A_n) < infinity$ 且 $union.big_n A_n = Omega$，那么称 $mu$ 是 *$sigma$-有限/$sigma$-Finite* 的。

一个关键的技巧是将一个一般的集合转化为一个单调递增的集合，或者一个互不相交的集合：令 $A_1' = A_1$，当 $n >= 2$ 的时候，令
$
    A_n' = union.big_(m=1)^n A_m text("or") A_n' = A_n inter (inter.big_(m=1)^(n-1) A_m^c) in cal(A),
$
这样，我们就可以不失一般性地假设要么 $A_n arrow.t Omega$，要么 $A_n$ 两两不交。

下面的结果帮助我们把定义在半代数 $cal(S)$ 上的测度扩展到它所生成的 $sigma$-代数 $sigma(cal(S))$。

#theorem("Carathéodory Extension Theorem")[
    令 $cal(S)$ 为一个半代数，$mu$ 定义在 $cal(S)$ 上并满足 $mu(diameter) = 0$。假设：
    1. 若 $S in cal(S)$ 可以写成有限个两两不交集合 $S_i in cal(S)$ 的并，则 $mu(S) = sum_i mu(S_i)$；
    2. 若 $S_i, S in cal(S)$ 且 $S = +_(i >= 1) S_i$，则 $mu(S) <= sum_(i >= 1) mu(S_i)$。
    则 $mu$ 存在唯一的一个扩张 $overline(mu)$，使其成为由 $cal(S)$ 生成的代数 $overline(cal(S))$ 上的测度。若 $overline(mu)$ 是 $sigma$-有限的，则还存在唯一的一个扩张 $nu$，使其成为 $sigma(cal(S))$ 上的测度。
]<label:theorem-1-1-3>

这意味着满足有限可加性以及可数次可加性的测度可以唯一地扩展到代数上，如果扩展后的测度是 $sigma$-有限的，那么还可以唯一地扩展到 $sigma$-代数上。这个定理证明很复杂，因此略过，或者可以查看实分析以及测度论的相关章节。为了检查定理中的第二个条件（可数次可加性），下面的引理是有用的：

#lemma()[
    假设 $cal(S)$ 是一个半代数，$mu$ 定义在 $cal(S)$ 上并满足 $mu(diameter) = 0$。$mu$ 有如下性质：如果 $S in sigma(cal(S))$ 且其可以写成有限个两两不交集合 $S_i in cal(S)$ 的并，则 $mu(S) = sum_i mu(S_i)$。那么下面这些结论成立：
    1. 若 $A, B_i in overline(S)$ 且 $A = +_(i=1)^n B_i$，则 $overline(mu)(A) = sum_i overline(mu)(B_i)$；
    2. 若 $A, B_i in overline(S)$ 且 $A subset union.big_(i=1)^n B_i$，则 $overline(mu)(A) <= sum_i overline(mu)(B_i)$。
]<label:lemma-1-1-2>

#proof()[
    关于第一条：由于 $B_i in overline(cal(S))$，所以 $B_i$ 可以写成 $cal(S)$ 中集合的有限个两两不交并，即 $B_i = +_j S_(i, j)$，其中 $S_(i, j) in cal(S)$。因此
    $
        overline(mu)(A) = overline(mu)(+_(i, j) S_(i, j)) = sum_(i, j) mu(S_(i, j)) = sum_i overline(mu)(B_i).
    $
    关于第二条：先考虑 $n = 1$ 的情形，此时 $B_1 = B$。注意到 $B = A + (B inter A^c)$，且 $B inter A^c in overline(cal(S))$，因此
    $
        overline(mu)(A) <= overline(mu)(A) + overline(mu)(B inter A^c) = overline(mu)(B).
    $
    将 $B_k$ 转化为互不相交的一列集合，令 $F_k = B_1^c inter ... inter B_(k-1)^c inter B_k$，并注意到 $union.big_i B_i = F_1 + ... + F_n$，以及 $A = A inter (union.big_i B_i) = (A inter F_1) + ... + (A inter F_n)$。于是利用第一条、以及在 $n=1$ 的情形下的第二条，再用一次第一条，得到
    $
        overline(mu)(A) = sum_(k=1)^n overline(mu)(A inter F_k) <= sum_(k=1)^n overline(mu)(F_k) = overline(mu)(union.big_i B_i).
    $
]

#proof("For Theorem 1.1.2")[
    令 $cal(S)$ 为半开矩形 $(a, b]$ 所组成的半代数，这里 $-oo <= a_i < b_i <= oo$。我们使用 @label:theorem-1-1-3 来证明。对于第一个条件，我们将区间 $(a, b]$ 进行细分，得到 $+_(i=1)^n (a_i, b_i]$，其中 $a_1 = a$、$b_n = b$，并且对于 $2 <= i <= n$，$a_i = b_(i-1)$。因此第一个条件显然成立。

    对于第二个条件，先不失一般性地假设 $-oo <= a_i < b_i <= oo$ 且 $(a, b] = union.big_(i >= 1) (a_i, b_i]$。选择 $delta > 0$，使得 $F(a + delta) < F(a) + epsilon$，并且选择 $eta_i$ 使得 $F(b_i + eta_i) < F(b_i) + epsilon * 2^(-i)$。开区间 $(a_i, b_i + eta_i)$ 覆盖 $[a + delta, b]$，因此存在一个 *有限子覆盖* $(alpha_j, beta_j)_1^J$。由于 $(a+delta, b] subset union.big_(j=1)^J (alpha_j, beta_j]$，使用 @label:lemma-1-1-2 的第二条，可以得到
    $
        F(b) - F(a + delta) <= sum_(j=1)^J F(beta_j) - F(alpha_j) <= sum_(i=1)^infinity F(b_i + eta_i) - F(a_i).
    $
    其中第二步是使用了子覆盖实际上是覆盖的一个细分。由于 $delta$ 与 $eta_i$ 的选取，我们就得到了
    $
        F(b) - F(a) <= 2 epsilon + sum_(i=1)^infinity F(b_i) - F(a_i).
    $
    最后，只需要注意到 $epsilon$ 是任意的，我们就可以将 $epsilon$ 去掉，从而证明了在 $-oo < a < b < oo$ 的情形下的结论。由于我们假设了 $(a, b]$ 的结构，其可以被一列半开矩形覆盖，只需要有下面观察：如果 $(a, b] subset union.big_i (a_i, b_i]$，且还有 $(A, B] subset (a, b]$ 满足 $-oo < A < B < oo$，则 $F(B) - F(A) <= sum_(i=1)^infinity F(b_i) - F(a_i)$。由于该不等式对于任意有限区间 $(A, B] subset (a, b]$ 都成立，因此我们就得到了在 $-oo <= a < b <= oo$ 的情形下的结论。
]

我们希望类似构建一下 $RR^d$ 上的测度函数，类似于 @label:theorem-1-1-2，第一步是给出定义函数的假设，类比 $d = 1$ 的情形，自然会假设：
1. $F$ 是单调不减的。若 $x <= y$，也就是对于所有的 $i$ 都有 $x_i <= y_i$，则 $F(x) <= F(y)$；
2. $F$ 是右连续的，即 $lim_(y arrow.b x) F(y) = F(x)$，这里 $y arrow.b x$ 表示每个分量都满足 $y_i arrow.b x_i$；
3. 若 $x_n arrow.b -infinity$，即每个坐标都趋于 $-infinity$，则 $F(x_n) arrow.b 0$，若 $x_n arrow.t infinity$，那么 $F(x_n) arrow.t 1$。
但是这样的限定是不足够的，仅仅保证在各个维度上的分布都是单调不减的，不能保证其在混合差分下的单调性。比如二维下的公式
$
    mu((a_1, b_1] times (a_2, b_2]) & = mu((-oo, b_1] times (-oo, b_2]) - mu((-oo, a_1] times (-oo, b_2]) \
                                    & "  "- mu((-oo, b_1] times (-oo, a_2]) + mu((-oo, a_1] times (-oo, a_2]) \
                                    & = F(b_1, b_2) - F(a_1, b_2) - F(b_1, a_2) + F(a_1, a_2).
$
这就必须引入一个新的条件：对于我们要求测度的半开矩形 $A = (a_1, b_1] times ... times (a_d, b_d]$，定义顶点集合 $V = {a_1, b_1} times ... times {a_d, b_d}$，对于每个 $v in V$ 定义
$
    op("sgn")(v) & = (-1)^(\#\{i: v_i = a_i\}) \
       Delta_A F & = sum_(v in V) op("sgn")(v) F(v).
$
这里 $op("sgn")$ 指的是这个顶点含有下界 $a_i$ 的坐标个数的奇偶性。令 $mu(A) = Delta_A F$，假设第四条：
4. 对所有矩形 $A$，都有 $Delta_A F >= 0$。

#theorem()[
    假设 $F: RR^d arrow [0, 1]$ 满足上面讲的四条条件，那么在 $(RR^d, cal(R)^d)$ 上存在一个唯一的概率测度 $mu$，使得对于所有有限矩形 $A$ 都有 $mu(A) = Delta_A F$。
]

#proof()[
    我们先对所有有限矩形定义 $mu(A) = Delta_A F$，然后利用单调性把定义扩展到 $cal(S)_d$ 上。
]

#pagebreak()

== Distributions

若 $X$ 是在 $Omega$ 上定义的 *实值函数*，如果对于 $RR$ 上的每个 Borel 集合 $B$，$X^(-1)(B) = \{ omega : X(omega) in B \} in cal(F)$，则其被称为一个 *随机变量/Random Variable*。如果我们需要强调所在的 $sigma$-域，我们会说 $X$ 是 $cal(F)$-可测的，或者 $X in cal(F)$。

如果 $Omega$ 是一个离散概率空间，那么任意的函数 $X: Omega -> RR$ 都是随机变量，指标函数也是一个经典且有用的随机变量例子：对于 $A in cal(F)$，定义
$
    bb(1)_A (omega) = cases(
        1 " if" omega in A,
        0 " if" omega in.not A
    ).
$
随机变量 $X$ 会在 $RR$ 上诱导一个概率测度，称为它的 *分布/Distribution*，对任意 Borel 集 $A$，定义为 $mu(A) = P(X in A) = P(X^(-1)(A))$。简单来讲，我们将 $RR$ 上的 Borel 集 $A$ 拉回到 $Omega$ 上的 $X^(-1)(A)$，然后对 $X^(-1)(A)$ 取概率 $P$。

验证 $mu$ 是一个概率测度：首先若 $A_i$ 两两不相交，则 $X^(-1)(A_i)$ 也是两两不相交的，因此
$
    mu (union.big_i A_i) = P(X in union.big_i A_i) = P(union.big_i {X in A_i}) = sum_i P(X in A_i) = sum_i mu(A_i).
$

随机变量 $X$ 的分布 $mu$ 通过其 *分布函数/Distribution Function* $F(x) = P(X <= x) = mu ((-oo, x])$ 来描述，任意分布函数都有丰富的性质：

#theorem()[
    任意分布函数 $F$ 都满足下面性质：
    1. $F$ 单调不减；
    2. $lim_(x -> oo) F(x) = 1$，且 $lim_(x -> -oo) F(x) = 0$；
    3. $F$ 右连续，即 $lim_(y arrow.b x) F(y) = F(x)$；
    4. 若 $F(x-) = lim_(y arrow.t x) F(y)$，则 $F(x-) = P(X < x)$；
    5. $P(X = x) = F(x) - F(x-)$。
]<label:theorem-1-2-1>

#proof()[
    1. 注意到若 $x <= y$，则 ${X <= x} subset {X <= y}$，再使用 $F(x) = P({X <= x})= mu((-oo, x]) <= mu((-oo, y]) = P({X <= y}) = F(y)$ 得证。
    2. 
]

/*
为证明 (ii)，注意若 $x ↑ ∞$，则 $ {X ≤ x} ↑ Omega$；而若 $x ↓ -∞$，则 $ {X ≤ x} ↓ ∅$，再用定理 1.1.1 的 (iii) 与 (iv)。

为证明 (iii)，注意若 $y ↓ x$，则 $ {X ≤ y} ↓ {X ≤ x}$。

为证明 (iv)，注意若 $y ↑ x$，则 $ {X ≤ y} ↑ {X < x}$。

对 (v)，注意
$
  P(X = x) = P(X ≤ x) - P(X < x),
$
并使用 (iii) 与 (iv)。∎

下面的结果表明：我们已经找到了刻画分布函数所需的、绰绰有余的性质。

*图 1.4* 定理 1.2.2 的证明中所定义“逆”的示意图。

*定理 1.2.2* 若 $F$ 满足定理 1.2.1 中的 (i)、(ii)、(iii)，则它是某个随机变量的分布函数。

*证明* 取 $Omega = (0, 1)$，$cal(F)$ 为 Borel 集，且 $P$ 为 Lebesgue 测度。对 $omega ∈ (0, 1)$，令
$
  X(omega) = sup{y: F(y) < omega}.
$

一旦我们证明
$
  (star) \quad {omega: X(omega) ≤ x} = {omega: omega ≤ F(x)},
$
结论立刻推出，因为 $P(omega: omega ≤ F(x)) = F(x)$。（回忆 $P$ 是 Lebesgue 测度。）为检验 (star)，注意若 $omega ≤ F(x)$，则 $X(omega) ≤ x$，因为此时 $x ∉ {y: F(y) < omega}$。另一方面，若 $omega > F(x)$，则由于 $F$ 右连续，存在 $epsilon > 0$ 使得 $F(x + epsilon) < omega$，从而 $X(omega) ≥ x + epsilon > x$。∎

尽管 $F$ 可能既不是一一映射也不是满射，我们仍把上面构造的 $X$ 称为 $F$ 的逆，并记为 $F^(-1)$。定理 1.2.2 证明中的方案在计算机上生成随机变量时非常有用：标准算法先生成服从均匀分布的随机变量 $U$，再应用定理 1.2.2 中的“逆分布函数”，得到随机变量 $F^(-1)(U)$，其分布函数为 $F$。

如果 $X$ 与 $Y$ 在 $(ℝ, cal(R))$ 上诱导同一个分布 $mu$，我们称 $X$ 与 $Y$ **同分布**（equal in distribution）。结合定理 1.1.4，这当且仅当 $X$ 与 $Y$ 有相同的分布函数，即对所有 $x$，
$
  P(X ≤ x) = P(Y ≤ x).
$
当 $X$ 与 $Y$ 同分布时，我们喜欢写
$
  X =_d Y,
$
并把它读作“$X$ 与 $Y$ 同分布”。

当分布函数 $F(x) = P(X ≤ x)$ 具有形式
$
  F(x) = ∫_-∞^x f(y) d y \quad (1.2.1)
$
时，我们称 $X$ 具有*密度函数* $f$。在记忆公式时，把 $f(x)$ 想成 $P(X = x)$ 往往是有帮助的，尽管
$
  P(X = x) = lim_(epsilon -> 0) ∫_(x - epsilon)^(x + epsilon) f(y) d y = 0.
$
应读者要求，我们不再沿用把密度函数写成 $P(X = x)$ 的旧习惯；取而代之，我们将使用像 $f_X(x)$ 这样既清晰又信息量充足的记号。

我们可以从 $f$ 出发，用 (1.2.1) 定义分布函数 $F$。为了最终得到一个分布函数，充要条件是 $f(x) ≥ 0$ 且 $∫ f(x) d x = 1$。下面三个例子在后文中会很重要：

*例 1.2.3（$(0, 1)$ 上的均匀分布）* $f(x) = 1$（当 $x ∈ (0, 1)$），否则为 0。其分布函数为
$
  F(x) =
  cases(
    0, x ≤ 0;
    x, 0 ≤ x ≤ 1;
    1, x > 1
  )
$

*例 1.2.4（参数为 $lambda$ 的指数分布）* $f(x) = lambda e^(-lambda x)$（当 $x ≥ 0$），否则为 0。其分布函数为
$
  F(x) =
  cases(
    0, x ≤ 0;
    1 - e^(-lambda x), x ≥ 0
  )
$

*例 1.2.5（标准正态分布）*
$
  f(x) = (2 pi)^(-1/2) exp(-x^2/2).
$
此时 $F(x)$ 没有闭式表达，但当 $x$ 很大时有下面有用的界：

*定理 1.2.6* 对 $x > 0$，
$
  (x^(-1) - x^(-3)) exp(-x^2/2)
  ≤ ∫_x^∞ exp(-y^2/2) d y
  ≤ x^(-1) exp(-x^2/2).
$

*证明* 令 $y = x + z$，并用 $exp(-z^2/2) ≤ 1$，得到
$
  ∫_x^∞ exp(-y^2/2) d y
  ≤ exp(-x^2/2) ∫_0^∞ exp(-x z) d z
  = x^(-1) exp(-x^2/2).
$

对另一个方向，注意到
$
  ∫_x^∞ (1 - 3 y^(-4)) exp(-y^2/2) d y
  = (x^(-1) - x^(-3)) exp(-x^2/2).
$
∎

$ℝ$ 上的分布函数若具有密度，则称为*绝对连续*（absolutely continuous）；若对应测度相对于 Lebesgue 测度是奇异的，则称为*奇异*（singular）。关于这些概念的更多内容见附录 A.4。一个奇异分布的例子是：

*例 1.2.7（Cantor 集上的“均匀分布”）* Cantor 集 $C$ 的构造为：先从 $[0, 1]$ 中删去 $(1/3, 2/3)$，再对剩下的每个区间删去其中间三分之一，如此迭代。我们通过规定
$F(x)=0$（当 $x ≤ 0$），$F(x)=1$（当 $x ≥ 1$），并令 $F(x)=1/2$（当 $x ∈ [1/3, 2/3]$），$F(x)=1/4$（当 $x ∈ [1/9, 2/9]$），$F(x)=3/4$（当 $x ∈ [7/9, 8/9]$），…… 来定义一个相应的分布函数。然后利用单调性把 $F$ 扩展到整个 $[0, 1]$。不存在任何 $f$ 使得 (1.2.1) 成立，因为那样的 $f$ 会在一个 Lebesgue 测度为 1 的集合上恒为 0。由定义立刻可见，对应测度满足 $mu(C^c) = 0$。

一个概率测度 $P$（或其对应的分布函数）称为*离散*（discrete），如果存在可数集 $S$ 使得 $P(S^c) = 0$。离散分布的最简单例子是：

*图 1.5* Cantor 分布函数。

*例 1.2.8（在 0 处的点质量）* $F(x)=1$（当 $x ≥ 0$），$F(x)=0$（当 $x < 0$）。

在第 1.6 节中，我们将看到 Bernoulli、Poisson 与几何分布。下一个例子表明：与离散概率测度对应的分布函数可能相当“狂野”。

*例 1.2.9（稠密不连续点）* 令 $q_1, q_2, ...$ 为有理数的一种枚举。取 $alpha_i > 0$ 且 $sum_(i=1)^∞ alpha_i = 1$，并令
$
  F(x) = sum_(i=1)^∞ alpha_i 1_[q_i, ∞)(x),
$
其中
$
  1_[theta, ∞)(x) =
  cases(
    1, x ∈ [theta, ∞);
    0, text("否则")
  )
$
是区间 $[theta, ∞)$ 的指标函数。

*/

== Random Variables

== Integration

== Properties of the Integral

== Expected Value

=== Inequalities

=== Integration to the Limit

=== Computing Expected Values

== Product Measures, Fubini's Theorem

= Laws of Large Numbers

== Independence

=== Sufficient Conditions for Independence

=== Independence, Distribution, and Expectation

=== Sums of Independent Random Variables

=== Constructing Independent Random Variables

== Weak Laws of Large Numbers

=== $L^2$ Weak Laws

=== Triangular Arrays

=== Truncation

== Borel-Cantelli Lemmas

== Strong Law of Large Numbers

== Convergence of Random Series\*

=== Rates of Convergence

=== Infinite Mean

== Renewal Theory\*

== Large Deviations\*

= Central Limit Theorems

== The De Moivre-Laplace Theorem

== Weak Convergence

== Characteristic Functions

=== Definition, Inversion Formula

=== Weak Convergence

=== Moments and Derivatives

=== Polya's Criterion\*

=== The Moment Problem\*

== Central Limit Theorems

=== i.i.d. Sequences

=== Triangular Arrays

=== Prime Divisors (Erdös-Kac)\*

=== Rates of Convergence (Berry-Esseen)\*

== Local Limit Theorems\*

== Poisson Convergence

=== The Basic Limit Theorem

=== Two Examples with Dependence

== Poisson Processes

=== Compound Poisson Processes

=== Thinning

=== Conditioning

== Stable Laws\*

== Infinitely Divisible Distributions\*

== Limit Theorems in $RR^d$

= Martingales

== Conditional Expectation

=== Examples

=== Properties

=== Regular Conditional Probabilities\*

== Martingales, Almost Sure Convergence

== Examples

=== Bounded Increments

=== Polya's Urn Scheme

=== Radon-Nikodym Derivatives

=== Branching Processes

== Doob's Inequality, Convergence in $L^p$, $p > 1$

== Square Integrable Martingales\*

== Uniform Integrability, Convergence in $L^1$

== Backwards Martingales

== Optional Stopping Theorems

=== Applications to Random Walks

== Combinatorics of Simple Random Walk\*

= Markov Chains

== Examples

== Construction, Markov Properties

== Recurrence and Transience

== Stationary Measures

== Asymptotic Behavior

== Periodicity, Tail $sigma$-Field\*

== General State Space\*

=== Recurrence and Transience

=== Stationary Measures

=== Convergence Theorem

=== GI/G/1 Queue
